// 定义单词类型
export enum WordType {
  Intro = 'Intro',
  Character = 'Character',
  Action = 'Action',
  Setting = 'Setting',
  Item = 'Item',
  Emotion = 'Emotion',
  Connector = 'Connector',
  Ending = 'Ending',
}

// 结构化单词数据
export interface StoryWord {
  content: string;
  type: WordType;
}

export const STRUCTURED_WORDS: StoryWord[] = [
  // Intro
  { content: 'Once upon a time', type: WordType.Intro },
  { content: 'In a galaxy far, far away', type: WordType.Intro },
  { content: 'It was a dark and stormy night', type: WordType.Intro },
  { content: 'Long ago in a distant land', type: WordType.Intro },
  { content: 'In a small village', type: WordType.Intro },
  { content: 'Deep in the forest', type: WordType.Intro },
  { content: 'On a cold winter morning', type: WordType.Intro },
  { content: 'Under the burning sun', type: WordType.Intro },
  { content: 'In the middle of the ocean', type: WordType.Intro },
  { content: 'At the edge of the world', type: WordType.Intro },
  { content: 'Before the dawn', type: WordType.Intro },
  { content: 'When the clock struck twelve', type: WordType.Intro },

  // Character
  { content: 'there lived a programmer', type: WordType.Character },
  { content: 'a mysterious stranger', type: WordType.Character },
  { content: 'a cat with a keyboard', type: WordType.Character },
  { content: 'a brave knight', type: WordType.Character },
  { content: 'a time traveler', type: WordType.Character },
  { content: 'a lonely robot', type: WordType.Character },
  { content: 'a wise old wizard', type: WordType.Character },
  { content: 'a curious child', type: WordType.Character },
  { content: 'a sleeping dragon', type: WordType.Character },
  { content: 'a lost alien', type: WordType.Character },
  { content: 'a dancing bear', type: WordType.Character },
  { content: 'a singing mermaid', type: WordType.Character },
  { content: 'a flying squirrel', type: WordType.Character },
  { content: 'a grumpy goblin', type: WordType.Character },
  { content: 'a beautiful princess', type: WordType.Character },
  { content: 'a wicked witch', type: WordType.Character },
  { content: 'a friendly ghost', type: WordType.Character },
  { content: 'a talking tree', type: WordType.Character },
  { content: 'a pirate captain', type: WordType.Character },
  { content: 'a space explorer', type: WordType.Character },
  { content: 'a ninja master', type: WordType.Character },
  { content: 'a tiny fairy', type: WordType.Character },
  { content: 'a giant ogre', type: WordType.Character },
  { content: 'a clever fox', type: WordType.Character },
  { content: 'a lazy panda', type: WordType.Character },
  { content: 'a magical unicorn', type: WordType.Character },
  { content: 'a brave firefighter', type: WordType.Character },
  { content: 'a brilliant scientist', type: WordType.Character },
  { content: 'a wandering bard', type: WordType.Character },
  { content: 'a secret agent', type: WordType.Character },
  { content: 'a master chef', type: WordType.Character },
  { content: 'a rock star', type: WordType.Character },
  { content: 'a lost puppy', type: WordType.Character },
  { content: 'a golden eagle', type: WordType.Character },
  { content: 'a snow leopard', type: WordType.Character },
  { content: 'a baby elephant', type: WordType.Character },
  { content: 'a mischievous monkey', type: WordType.Character },
  { content: 'a gentle giant', type: WordType.Character },
  { content: 'a fearless warrior', type: WordType.Character },
  { content: 'a dark sorcerer', type: WordType.Character },
  { content: 'a cybernetic human', type: WordType.Character },
  { content: 'a mutant superhero', type: WordType.Character },

  // Action
  { content: 'started coding furiously', type: WordType.Action },
  { content: 'found a hidden treasure', type: WordType.Action },
  { content: 'opened the magic door', type: WordType.Action },
  { content: 'lost the key', type: WordType.Action },
  { content: 'made a cup of coffee', type: WordType.Action },
  { content: 'looked at the stars', type: WordType.Action },
  { content: 'ran away from home', type: WordType.Action },
  { content: 'saved the world', type: WordType.Action },
  { content: 'cast a powerful spell', type: WordType.Action },
  { content: 'built a rocket ship', type: WordType.Action },
  { content: 'wrote a love letter', type: WordType.Action },
  { content: 'danced in the rain', type: WordType.Action },
  { content: 'planted a magical seed', type: WordType.Action },
  { content: 'climbed a high mountain', type: WordType.Action },
  { content: 'swam across the river', type: WordType.Action },
  { content: 'flew into the sky', type: WordType.Action },
  { content: 'jumped over the moon', type: WordType.Action },
  { content: 'sang a beautiful song', type: WordType.Action },
  { content: 'painted a masterpiece', type: WordType.Action },
  { content: 'cooked a delicious meal', type: WordType.Action },
  { content: 'read a mysterious book', type: WordType.Action },
  { content: 'solved a difficult puzzle', type: WordType.Action },
  { content: 'defeated the monster', type: WordType.Action },
  { content: 'fixed the broken machine', type: WordType.Action },
  { content: 'discovered a new planet', type: WordType.Action },
  { content: 'invented a time machine', type: WordType.Action },
  { content: 'learned a new language', type: WordType.Action },
  { content: 'baked a chocolate cake', type: WordType.Action },
  { content: 'played a prank', type: WordType.Action },
  { content: 'caught a falling star', type: WordType.Action },
  { content: 'befriended a dragon', type: WordType.Action },
  { content: 'traveled to the future', type: WordType.Action },
  { content: 'escaped from prison', type: WordType.Action },
  { content: 'won the lottery', type: WordType.Action },
  { content: 'became king', type: WordType.Action },
  { content: 'lost their memory', type: WordType.Action },
  { content: 'found true love', type: WordType.Action },
  { content: 'started a revolution', type: WordType.Action },
  { content: 'stopped a war', type: WordType.Action },
  { content: 'healed the sick', type: WordType.Action },
  { content: 'controlled the weather', type: WordType.Action },
  { content: 'summoned a demon', type: WordType.Action },
  { content: 'talked to animals', type: WordType.Action },
  { content: 'walked through walls', type: WordType.Action },
  { content: 'became invisible', type: WordType.Action },
  { content: 'flew without wings', type: WordType.Action },

  // Setting
  { content: 'under the moonlight', type: WordType.Setting },
  { content: 'in a secret garden', type: WordType.Setting },
  { content: 'in a crowded city', type: WordType.Setting },
  { content: 'in a quiet library', type: WordType.Setting },
  { content: 'in a dark cave', type: WordType.Setting },
  { content: 'on a floating island', type: WordType.Setting },
  { content: 'in a futuristic city', type: WordType.Setting },
  { content: 'in a magical forest', type: WordType.Setting },
  { content: 'under the sea', type: WordType.Setting },
  { content: 'in the clouds', type: WordType.Setting },
  { content: 'in a dream', type: WordType.Setting },
  { content: 'in a parallel universe', type: WordType.Setting },
  { content: 'in a haunted house', type: WordType.Setting },
  { content: 'on a spaceship', type: WordType.Setting },
  { content: 'in a submarine', type: WordType.Setting },
  { content: 'in a volcano', type: WordType.Setting },
  { content: 'in a desert oasis', type: WordType.Setting },
  { content: 'in a snowy wasteland', type: WordType.Setting },
  { content: 'in a busy market', type: WordType.Setting },
  { content: 'in a peaceful meadow', type: WordType.Setting },
  { content: 'under a waterfall', type: WordType.Setting },
  { content: 'inside a computer', type: WordType.Setting },
  { content: 'on a rainbow', type: WordType.Setting },
  { content: 'in a crystal palace', type: WordType.Setting },
  { content: 'in a time loop', type: WordType.Setting },
  { content: 'in a black hole', type: WordType.Setting },

  // Item
  { content: 'holding a glowing sword', type: WordType.Item },
  { content: 'wearing a red cloak', type: WordType.Item },
  { content: 'carrying an ancient book', type: WordType.Item },
  { content: 'riding a flying carpet', type: WordType.Item },
  { content: 'wearing a golden crown', type: WordType.Item },
  { content: 'holding a magic wand', type: WordType.Item },
  { content: 'carrying a heavy bag', type: WordType.Item },
  { content: 'riding a white horse', type: WordType.Item },
  { content: 'driving a fast car', type: WordType.Item },
  { content: 'using a super computer', type: WordType.Item },
  { content: 'wearing a space suit', type: WordType.Item },
  { content: 'holding a treasure map', type: WordType.Item },
  { content: 'playing a guitar', type: WordType.Item },
  { content: 'holding a flower', type: WordType.Item },
  { content: 'wearing sunglasses', type: WordType.Item },
  { content: 'holding a crystal ball', type: WordType.Item },
  { content: 'wearing a jetpack', type: WordType.Item },
  { content: 'carrying a lantern', type: WordType.Item },
  { content: 'riding a dragon', type: WordType.Item },
  { content: 'holding a lightsaber', type: WordType.Item },
  { content: 'wearing a mask', type: WordType.Item },
  { content: 'carrying a shield', type: WordType.Item },
  { content: 'using a grappling hook', type: WordType.Item },
  { content: 'holding a potion', type: WordType.Item },
  { content: 'wearing invisibility cloak', type: WordType.Item },
  { content: 'carrying a compass', type: WordType.Item },
  { content: 'holding a key', type: WordType.Item },
  { content: 'wearing a ring of power', type: WordType.Item },

  // Emotion
  { content: 'feeling happy', type: WordType.Emotion },
  { content: 'feeling sad', type: WordType.Emotion },
  { content: 'feeling excited', type: WordType.Emotion },
  { content: 'feeling scared', type: WordType.Emotion },
  { content: 'feeling tired', type: WordType.Emotion },
  { content: 'feeling hungry', type: WordType.Emotion },
  { content: 'feeling lonely', type: WordType.Emotion },
  { content: 'feeling brave', type: WordType.Emotion },
  { content: 'full of hope', type: WordType.Emotion },
  { content: 'full of joy', type: WordType.Emotion },
  { content: 'with great courage', type: WordType.Emotion },
  { content: 'with a heavy heart', type: WordType.Emotion },
  { content: 'with a big smile', type: WordType.Emotion },
  { content: 'with tears in their eyes', type: WordType.Emotion },
  { content: 'exhausted but happy', type: WordType.Emotion },
  { content: 'lost in thought', type: WordType.Emotion },
  { content: 'filled with rage', type: WordType.Emotion },
  { content: 'trembling with fear', type: WordType.Emotion },
  { content: 'bursting with laughter', type: WordType.Emotion },
  { content: 'silent and watchful', type: WordType.Emotion },
  { content: 'peaceful and calm', type: WordType.Emotion },
  { content: 'confused and lost', type: WordType.Emotion },
  { content: 'determined to win', type: WordType.Emotion },
  { content: 'ready for anything', type: WordType.Emotion },

  // Connector
  { content: ',', type: WordType.Connector },
  { content: '.', type: WordType.Connector },
  { content: '!', type: WordType.Connector },
  { content: '?', type: WordType.Connector },
  { content: '...', type: WordType.Connector },
  { content: ';', type: WordType.Connector },
  { content: ':', type: WordType.Connector },
  { content: 'and', type: WordType.Connector },
  { content: 'but', type: WordType.Connector },
  { content: 'or', type: WordType.Connector },
  { content: 'so', type: WordType.Connector },
  { content: 'because', type: WordType.Connector },
  { content: 'then', type: WordType.Connector },
  { content: 'he', type: WordType.Connector },
  { content: 'she', type: WordType.Connector },
  { content: 'it', type: WordType.Connector },
  { content: 'they', type: WordType.Connector },
  { content: 'we', type: WordType.Connector },
  { content: 'I', type: WordType.Connector },
  { content: 'you', type: WordType.Connector },
  { content: 'his', type: WordType.Connector },
  { content: 'her', type: WordType.Connector },
  { content: 'its', type: WordType.Connector },
  { content: 'their', type: WordType.Connector },
  { content: 'our', type: WordType.Connector },
  { content: 'my', type: WordType.Connector },
  { content: 'your', type: WordType.Connector },
  { content: 'but suddenly', type: WordType.Connector },
  { content: 'meanwhile', type: WordType.Connector },
  { content: 'however', type: WordType.Connector },
  { content: 'unexpectedly', type: WordType.Connector },
  { content: 'as a result', type: WordType.Connector },
  { content: 'at that moment', type: WordType.Connector },
  { content: 'just then', type: WordType.Connector },
  { content: 'without warning', type: WordType.Connector },
  { content: 'strangely enough', type: WordType.Connector },
  { content: 'believe it or not', type: WordType.Connector },
  { content: 'unfortunately', type: WordType.Connector },
  { content: 'luckily', type: WordType.Connector },
  { content: 'in the end', type: WordType.Connector },
  { content: 'after a while', type: WordType.Connector },
  { content: 'before long', type: WordType.Connector },
  { content: 'despite the danger', type: WordType.Connector },
  { content: 'against all odds', type: WordType.Connector },
  { content: 'during the storm', type: WordType.Connector },
  { content: 'at midnight', type: WordType.Connector },
  { content: 'before the dawn', type: WordType.Connector },
  { content: 'under the scorching sun', type: WordType.Connector },
  { content: 'in the pouring rain', type: WordType.Connector },
  { content: 'on a foggy morning', type: WordType.Connector },
  { content: 'during a blizzard', type: WordType.Connector },
  { content: 'when the wind blew', type: WordType.Connector },
  { content: 'as the snow fell', type: WordType.Connector },
  { content: 'in the heat of summer', type: WordType.Connector },
  { content: 'on a crisp autumn day', type: WordType.Connector },
  { content: 'when the moon was full', type: WordType.Connector },
  { content: 'at the break of day', type: WordType.Connector },
  { content: 'in the dead of night', type: WordType.Connector },
  { content: 'to find the truth', type: WordType.Connector },
  { content: 'to save the princess', type: WordType.Connector },
  { content: 'for revenge', type: WordType.Connector },
  { content: 'out of curiosity', type: WordType.Connector },
  { content: 'to prove them wrong', type: WordType.Connector },
  { content: 'to break the curse', type: WordType.Connector },
  { content: 'to find a way home', type: WordType.Connector },
  { content: 'to protect the innocent', type: WordType.Connector },
  { content: 'to seek their fortune', type: WordType.Connector },
  { content: 'to escape their past', type: WordType.Connector },
  { content: 'for the glory', type: WordType.Connector },
  { content: 'because of a promise', type: WordType.Connector },
  { content: 'in search of adventure', type: WordType.Connector },
  { content: 'to fulfill a destiny', type: WordType.Connector },
  { content: 'with a loud bang', type: WordType.Connector },
  { content: 'in silence', type: WordType.Connector },
  { content: 'smelling of roses', type: WordType.Connector },
  { content: 'whispering softly', type: WordType.Connector },
  { content: 'hearing a strange noise', type: WordType.Connector },
  { content: 'feeling the cold wind', type: WordType.Connector },
  { content: 'seeing a bright light', type: WordType.Connector },
  { content: 'tasting sweet victory', type: WordType.Connector },
  { content: 'with a thunderous roar', type: WordType.Connector },
  { content: 'smelling like old books', type: WordType.Connector },
  { content: 'feeling the ground shake', type: WordType.Connector },
  { content: 'hearing a distant melody', type: WordType.Connector },
  { content: 'blinded by the light', type: WordType.Connector },
  { content: 'deafening silence', type: WordType.Connector },
  { content: 'with a smile', type: WordType.Connector },
  { content: 'without a sound', type: WordType.Connector },
  { content: 'unexpectedly', type: WordType.Connector },
  { content: 'suddenly', type: WordType.Connector },

  // Ending
  { content: 'forever and ever', type: WordType.Ending },
  { content: 'happily ever after', type: WordType.Ending },
  { content: 'The End', type: WordType.Ending },
  { content: 'and then woke up', type: WordType.Ending },
  { content: 'to be continued...', type: WordType.Ending },
  { content: 'and they lived in peace', type: WordType.Ending },
  { content: 'and the world was safe', type: WordType.Ending },
  { content: 'and the adventure continued', type: WordType.Ending },
  { content: 'and nothing was the same', type: WordType.Ending },
  { content: 'and they never looked back', type: WordType.Ending },
];

// 推荐逻辑
export const getRecommendedTypes = (lastType?: WordType): WordType[] => {
  if (!lastType) return [WordType.Intro];

  switch (lastType) {
    case WordType.Intro:
      return [WordType.Character, WordType.Setting];
    case WordType.Character:
      return [WordType.Action, WordType.Emotion, WordType.Item];
    case WordType.Action:
      return [WordType.Setting, WordType.Connector, WordType.Item, WordType.Ending];
    case WordType.Setting:
      return [WordType.Action, WordType.Character, WordType.Connector, WordType.Ending];
    case WordType.Item:
      return [WordType.Action, WordType.Connector, WordType.Setting];
    case WordType.Emotion:
      return [WordType.Action, WordType.Connector];
    case WordType.Connector:
      return [WordType.Action, WordType.Character, WordType.Setting, WordType.Emotion];
    default:
      return Object.values(WordType);
  }
};
